# Generated by Django 5.1.3 on 2025-01-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default=1, max_length=3, verbose_name='Valyuta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Chegirma narxini kiriting. Masalan: 10000', max_digits=10, verbose_name='Chegirma narxi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='manager.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('l', 'l'), ('ml', 'ml')], max_length=2, verbose_name="O'lchov birligi"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manager.product', verbose_name='Mahsuloti'),
        ),
    ]
