# Generated by Django 5.1.3 on 2025-01-24 03:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_product_currency_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='manager.departament', verbose_name="Bo'limi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='manager.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default="Ma'lumot qo'shilmadi.", verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='Agar mahsulotingizga chegirma qo‘ymoqchi bo‘lsangiz, chegirma foizini (masalan, 50) kiriting. Agar chegirma bermoqchi bo‘lmasangiz, bu maydonga tegmang.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('mg', 'Milligram'), ('l', 'Litr'), ('ml', 'Milliliter')], max_length=2, verbose_name="O'lchov birligi"),
        ),
    ]
