# Generated by Django 5.1.3 on 2025-01-31 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_category_departament_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_uz',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AddField(
            model_name='departament',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='departament',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='departament',
            name='slug_en',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AddField(
            model_name='departament',
            name='slug_uz',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default="Ma'lumot qo'shilmadi.", null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default="Ma'lumot qo'shilmadi.", null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_uz',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS')], max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='Agar mahsulotingizga chegirma qo‘ymoqchi bo‘lsangiz, chegirma foizini (masalan, 50) kiriting. Agar chegirma bermoqchi bo‘lmasangiz, bu maydonga tegmang.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Rasmning o‘lchami 500x350 piksel bo‘lishi kerak. Iltimos, to‘g‘ri o‘lchamdagi rasmni yuklang!', upload_to='products/', verbose_name='Rasmi (500x350)'),
        ),
    ]
